### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by chiyuki0325** [TheGreatRambler/toost#12]
Distribution: Arch Linux
gcc version: 11.2.0

At first when compiling, decrypt.cpp encountered memcpy undeclared error, when I added "`#include <cstring>` to decrypt.h, the program could be compiled normally, but encountered the following error when executing：
```
terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::to_bytes
```

**Comment by chiyuki0325** [comment]
I don't know C++, but this seems to be an issue of LevelParser.cpp
```
std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> stringConverter;
```

**Comment by TheGreatRambler** [comment]
What level codes have you tested on?

**Comment by chiyuki0325** [comment]
I got this error on every level

**Comment by TheGreatRambler** [comment]
Turns out `wchar_t` is the wrong size on linux (perhaps it's 4 bytes not 2? Not sure) but changing to `int16_t` in the most recent build worked
