### ISSUE TITLE
Crash while drawing some map

### ISSUE THREAD

**Issue by huaimogu** [TheGreatRambler/toost#13]
Distribution: windows 10/windows 11
hi, when i view a course,the application is crashed, the course id is P52-3WX-S2G,and the last debug info is:
Printing tile X:1 Y:43
Printing tile X:1 Y:43
Printing tile X:2 Y:23
Printing tile X:3 Y:22
Printing tile X:2 Y:21
Printing tile X:3 Y:22
Printing tile X:3 Y:22
Printing tile X:3 Y:22
Printing tile X:2 Y:23
Printing tile X:12 Y:0
Printing tile X:11 Y:0
Printing 11153741 at X:1392 Y:368 with W:16 and H:16
Printing 11153741 at X:1408 Y:368 with W:16 and H:16
Printing 11153741 at X:1424 Y:368 with W:16 and H:16
Printing 11153741 at X:1440 Y:368 with W:16 and H:16
Printing 11153741 at X:1456 Y:368 with W:16 and H:16

**Comment by TheGreatRambler** [comment]
It no longer crashes in the most recent release
