### ISSUE TITLE
Segmentation fault on Arch Linux

### ISSUE THREAD

**Issue by chiyuki0325** [TheGreatRambler/toost#14]
![图片](https://user-images.githubusercontent.com/73830635/184056834-4fae166e-b85e-434f-8f00-4c8d7afa6b7f.png)

```
$ LD_LIBRARY_PATH="$(pwd)/../lib" ./toost --path course_data_163.bcd --overworld ./qwq.png
Done parsing 4r4r
zsh: segmentation fault (core dumped)  LD_LIBRARY_PATH="$(pwd)/../lib" ./toost --path course_data_163.bcd --overworl
```

```
Stack trace of thread 7222:
#0  0x00007f3a60f649d9 cairo_ft_font_face_create_for_ft_face (libcairo.so.2 + 0xd09d9)
#1  0x000056016fe27e82 n/a (/home/yidaozhan/bin/toost + 0x1be82)
ELF object binary architecture: AMD x86-64
```

**Comment by chiyuki0325** [comment]
Same error occured after downgraded to cairo 1.16.0

```
Stack trace of thread 8156:
#0  0x00007fb5821325dc n/a (/home/yidaozhan/lib/libcairo.so.2 + 0xc45dc)
ELF object binary architecture: AMD x86-64
```

**Comment by TheGreatRambler** [comment]
Do you have the `font` folder relative to the `bin` folder like in the release zip? It needs to be one directory down from the executable and up one directory in the font folder

**Comment by chiyuki0325** [comment]
![图片](https://user-images.githubusercontent.com/73830635/184316618-6f511bff-293a-40bd-8be8-81d0b1a9a7bc.png)
I tried changing the directory structure like this but it still crashes

**Comment by TheGreatRambler** [comment]
Can you share the level file? I'll take a closer look tomorrow

**Comment by chiyuki0325** [comment]
This error happens on every level, probably because Arch Linux's library is too new

**Comment by chiyuki0325** [comment]
All files need to be placed under /usr for it to work (similar to file structure in the Debian package)
I also packaged for Arch Linux: https://aur.archlinux.org/packages/toost
