### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by balls69** [TheGreatRambler/toost#17]
Every level code i enter i get the level id could not be downloaded error. YEs it is a level code for Super Mario Maker 2.

**Comment by TheGreatRambler** [comment]
Does `tgrcode.com/mm2/level_info/XXX-XXX-XXX` for each level code work?

**Comment by ShadowJak** [comment]
It looks like downloading isn't working anymore.

https://tgrcode.com/mm2/level_info/9WF-FHM-1KF is an example that should work, but doesn't.

**Comment by TheGreatRambler** [comment]
The API has been down for a couple of days because of a game update breaking it, it should be up by Tuesday
