### ISSUE TITLE
Level ID XXXXXXXXX could not be downloaded

### ISSUE THREAD

**Issue by unsightedmetal6** [TheGreatRambler/toost#2]
Hi. I decided to try this SMM2 level viewer because the other one by JiXiaomai stopped working for me even though it was working before.

When I type in the level code and click "Download Level", I get a very quick error message that says "Level ID XXXXXXXXX could not be downloaded", where the XXXXXXXXX is the code.

It still creates a .BCD file, but when I attempt to load it, it gives another quick error: "Level file could not be parsed." By quick error, I mean it appears and disappears almost instantly, and I had to record my screen in order to read it.

I'm guessing that something stopped working on the server's end.

**Comment by TheGreatRambler** [comment]
If you try https://tgrcode.com/mm2/level_data/XXXXXXXXX you'll see it's a maker code, not a level code. The temp.bcd is always created, it's essentially a temporary file, but is just an empty file if it's not a valid level. The message lasts for 3 seconds, I was not sure if that was long enough

**Comment by unsightedmetal6** [comment]
When I go to the website, it says `This domain was recently registered at Namecheap.com. Please check back later!`

Is the website and software working for everyone else?

**Comment by TheGreatRambler** [comment]
The domain name nearly expired, but I've renewed it a few days ago. Most
regions should be fixed but I'll check

**Comment by unsightedmetal6** [comment]
It works now!
