### ISSUE TITLE
Level cannot be downloaded

### ISSUE THREAD

**Issue by bilago** [TheGreatRambler/toost#4]
Tried to access the level viewer and get an error that "Could not be downloaded"

https://tgrcode.com/mm2/level_info/jgrk230dg

this returns json that this is a valid level, and not a maker code.

https://tgrcode.com/mm2/level_data/JGRK230DG
and
https://tgrcode.com/mm2/level_data/JGR-K23-0DG
returns System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by bilago** [comment]
Well its working again now, so I guess it was a hiccup in the system. Closing as non issue currently

**Comment by TheGreatRambler** [comment]
Sorry, I make a lot of unannounced changes to the API lol
