### ISSUE TITLE
Certain levels dont work with this level viewer

### ISSUE THREAD

**Issue by PlaidXe** [TheGreatRambler/toost#7]
I have tried a few levels. two seem to work but most don't. I keep getting an Internal sever error or Level ID could not be downloaded. I tried both JiXiaomai's program and your website both result in errors.

**Only two levels that seem to work** 
C81-8H4-RGG
SQG-9NT-9GF

**Levels that don't work**
5BJ-G6X-LSG 
S0Q-MRG-5GG
FXY-QKH-41G
NJ0-0TF-4CG
XFP-RLF-MGF
XGM-H9L-0CG
LB7-LDG-KJG
BRG-477-VYG
0BH-621-HJF
MKV-L45-TTG

**Comment by TheGreatRambler** [comment]
There was an outage yesterday that I believe I've fixed
