### ISSUE TITLE
Build issues on Ubuntu (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by burritosoftware** [TheGreatRambler/toost#8]
Hey there, I have all the dependencies required for Desktop/CLI build as mentioned in your README and I have tried to run `make BUILD=release` but have run into a couple issues trying to build for Linux on WSL (Windows Subsystem):

1. I am trying to use GCC and then got an `make: c++: Command not found`. Looking it up I switched your `c++` in your Makefile to `gcc` which seemed to fix that issue.

2. Then, I got this from GCC:  
`gcc: error: unrecognized command line option ‘-std=gnu++20’; did you mean ‘-std=gnu++2a’?`  
Googling it showed me that I have to change compiler options, but that was weird as I thought they should be correctly set in the Makefile, however I edited that and moved on.

3. I got yet another error from GCC:
`gcc: error: unrecognized command line option ‘-mconsole’`  
I removed this argument and it moved on from that error.

 4. `collect2: error: ld returned 1 exit status`
 After seeing this, I'm not sure how to proceed. Is there a potential that the Makefile is incorrect?

**Comment by TheGreatRambler** [comment]
I never tested on linux, this seems like a host of linux issues. The first seems like a linux specific issue, the second seems like an out of date GCC compiler, the third seems like a windows flag leaking into the build, and the fourth seems like a result of the third issue

**Comment by TheGreatRambler** [comment]
I would gladly accept a PR if you find fixes, just make sure to lock those changes behind a linux check

**Comment by burritosoftware** [comment]
Is it possible for you to automatically ship builds using GitHub Actions? (then you can have autobuilds for Linux)

I'm not sure about fixes but I'd like to integrate Toost into my project over at https://github.com/burritosoftware/Nerdtendo but I need a Linux version

**Comment by TheGreatRambler** [comment]
I've managed to fix this issue in the most recent release, WSL doesn't have recent versions of GCC so that explained the errors.
